FROM python:3.10.0-alpine3.15

COPY ./src/requirements.txt /root/FlaskExmp/src/requirements.txt
RUN chown -R root:root /root/FlaskExmp

WORKDIR /root/FlaskExmp/src
RUN pip3 install -r requirements.txt

COPY ./src/ ./
RUN chown -R root:root ./

ENV FLASK_APP run.py

RUN chmod +x run.py
CMD ["python3", "run.py"]
